export type GlobePlace = { name: string; lat: number; lon: number };

export const GLOBE_PLACES: GlobePlace[] = [
	{ name: 'United States', lat: 38, lon: -97 },
	{ name: 'Canada', lat: 56, lon: -106 },
	{ name: 'Mexico', lat: 23, lon: -102 },
	{ name: 'Guatemala', lat: 15, lon: -90 },
	{ name: 'Costa Rica', lat: 10, lon: -84 },
	{ name: 'Panama', lat: 9, lon: -80 },
	{ name: 'Cuba', lat: 22, lon: -79 },
	{ name: 'Jamaica', lat: 18, lon: -77 },
	{ name: 'Dominican Republic', lat: 19, lon: -70 },
	{ name: 'Puerto Rico', lat: 18, lon: -66 },
	{ name: 'Colombia', lat: 4, lon: -73 },
	{ name: 'Venezuela', lat: 8, lon: -66 },
	{ name: 'Ecuador', lat: -1, lon: -78 },
	{ name: 'Peru', lat: -10, lon: -76 },
	{ name: 'Bolivia', lat: -17, lon: -65 },
	{ name: 'Brazil', lat: -10, lon: -52 },
	{ name: 'Paraguay', lat: -23, lon: -58 },
	{ name: 'Uruguay', lat: -33, lon: -56 },
	{ name: 'Argentina', lat: -34, lon: -64 },
	{ name: 'Chile', lat: -33, lon: -71 },
	{ name: 'United Kingdom', lat: 54, lon: -2 },
	{ name: 'Ireland', lat: 53, lon: -8 },
	{ name: 'Portugal', lat: 39, lon: -8 },
	{ name: 'Spain', lat: 40, lon: -4 },
	{ name: 'France', lat: 46, lon: 2 },
	{ name: 'Belgium', lat: 51, lon: 4 },
	{ name: 'Netherlands', lat: 52, lon: 5 },
	{ name: 'Germany', lat: 51, lon: 10 },
	{ name: 'Switzerland', lat: 47, lon: 8 },
	{ name: 'Italy', lat: 42, lon: 13 },
	{ name: 'Austria', lat: 47, lon: 14 },
	{ name: 'Czechia', lat: 50, lon: 15 },
	{ name: 'Poland', lat: 52, lon: 19 },
	{ name: 'Hungary', lat: 47, lon: 19 },
	{ name: 'Croatia', lat: 45, lon: 16 },
	{ name: 'Serbia', lat: 44, lon: 21 },
	{ name: 'Romania', lat: 46, lon: 25 },
	{ name: 'Bulgaria', lat: 43, lon: 25 },
	{ name: 'Greece', lat: 39, lon: 22 },
	{ name: 'Denmark', lat: 56, lon: 10 },
	{ name: 'Norway', lat: 61, lon: 9 },
	{ name: 'Sweden', lat: 62, lon: 15 },
	{ name: 'Finland', lat: 64, lon: 26 },
	{ name: 'Estonia', lat: 59, lon: 26 },
	{ name: 'Latvia', lat: 57, lon: 25 },
	{ name: 'Lithuania', lat: 55, lon: 24 },
	{ name: 'Belarus', lat: 53, lon: 28 },
	{ name: 'Ukraine', lat: 49, lon: 32 },
	{ name: 'Turkey', lat: 39, lon: 35 },
	{ name: 'Russia', lat: 60, lon: 90 },
	{ name: 'Morocco', lat: 32, lon: -6 },
	{ name: 'Algeria', lat: 28, lon: 3 },
	{ name: 'Tunisia', lat: 34, lon: 9 },
	{ name: 'Egypt', lat: 27, lon: 30 },
	{ name: 'Senegal', lat: 14, lon: -14 },
	{ name: 'Ivory Coast', lat: 8, lon: -5 },
	{ name: 'Ghana', lat: 8, lon: -1 },
	{ name: 'Nigeria', lat: 10, lon: 8 },
	{ name: 'Cameroon', lat: 6, lon: 12 },
	{ name: 'Ethiopia', lat: 9, lon: 40 },
	{ name: 'Uganda', lat: 1, lon: 32 },
	{ name: 'Kenya', lat: 0, lon: 38 },
	{ name: 'Tanzania', lat: -6, lon: 35 },
	{ name: 'Angola', lat: -12, lon: 17 },
	{ name: 'Zambia', lat: -13, lon: 28 },
	{ name: 'Zimbabwe', lat: -19, lon: 29 },
	{ name: 'Mozambique', lat: -18, lon: 35 },
	{ name: 'South Africa', lat: -29, lon: 24 },
	{ name: 'Israel', lat: 31, lon: 35 },
	{ name: 'Jordan', lat: 31, lon: 36 },
	{ name: 'Lebanon', lat: 34, lon: 36 },
	{ name: 'Iraq', lat: 33, lon: 44 },
	{ name: 'Kuwait', lat: 29, lon: 47 },
	{ name: 'Saudi Arabia', lat: 24, lon: 45 },
	{ name: 'Qatar', lat: 25, lon: 51 },
	{ name: 'United Arab Emirates', lat: 24, lon: 54 },
	{ name: 'Iran', lat: 32, lon: 53 },
	{ name: 'Kazakhstan', lat: 48, lon: 68 },
	{ name: 'Pakistan', lat: 30, lon: 70 },
	{ name: 'India', lat: 22, lon: 79 },
	{ name: 'Nepal', lat: 28, lon: 84 },
	{ name: 'Bangladesh', lat: 24, lon: 90 },
	{ name: 'Sri Lanka', lat: 7, lon: 81 },
	{ name: 'Myanmar', lat: 21, lon: 96 },
	{ name: 'Thailand', lat: 15, lon: 101 },
	{ name: 'Cambodia', lat: 12, lon: 105 },
	{ name: 'Vietnam', lat: 16, lon: 108 },
	{ name: 'Malaysia', lat: 4, lon: 102 },
	{ name: 'Singapore', lat: 1, lon: 104 },
	{ name: 'Indonesia', lat: -2, lon: 118 },
	{ name: 'Philippines', lat: 13, lon: 122 },
	{ name: 'Hong Kong', lat: 22, lon: 114 },
	{ name: 'Taiwan', lat: 24, lon: 121 },
	{ name: 'China', lat: 35, lon: 105 },
	{ name: 'Mongolia', lat: 46, lon: 105 },
	{ name: 'South Korea', lat: 36, lon: 128 },
	{ name: 'Japan', lat: 36, lon: 138 },
	{ name: 'Papua New Guinea', lat: -6, lon: 145 },
	{ name: 'Australia', lat: -25, lon: 134 },
	{ name: 'New Zealand', lat: -41, lon: 174 },
	{ name: 'Fiji', lat: -18, lon: 178 }
];
